version: '3.2'
services:
  postgres:
    image: skyscanner-clone_postgres
    environment:
      POSTGRES_DB: air
      POSTGRES_PASSWORD: airlock
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
  airplane-react:
    image: skyscanner-clone_airplane-react
    volumes:
      - '/usr/src/app/node_modules'
    command: ["./wait-for-it.sh", "airplane-spring-boot:3001", "--", "npm", "start", "-p", "3000", "-b", "0.0.0.0"]
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=development
      - REACT_APP_BACKEND_URL=http://${HOST_IP}:3001
    tty: true
    depends_on:
      - airplane-spring-boot
  airplane-spring-boot:
    image: skyscanner-clone_airplane-spring-boot
    restart: always
    command: ["./wait-for-it.sh", "postgres:5432", "--", "java",  "-jar", "/app.jar"]
    depends_on:
      - postgres
    ports:
      - "3001:8080"
